//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn
{
    using System;
    using System.Collections.Generic;
    
    public partial class BangLuong
    {
        public int MaBangLuong { get; set; }
        public Nullable<int> MaNhanVien { get; set; }
        public Nullable<int> Thang { get; set; }
        public Nullable<int> Nam { get; set; }
        public Nullable<int> SoNgayCong { get; set; }
        public Nullable<decimal> PhuCap { get; set; }
        public Nullable<decimal> Thuong { get; set; }
        public Nullable<decimal> KhauTru { get; set; }
        public Nullable<decimal> ThucLinh { get; set; }
        public string TrangThaiThanhToan { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
