//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhGiaHieuSuat
    {
        public int MaDanhGia { get; set; }
        public Nullable<int> MaNhanVien { get; set; }
        public string KyDanhGia { get; set; }
        public Nullable<System.DateTime> NgayDanhGia { get; set; }
        public Nullable<int> DiemSo { get; set; }
        public string NhanXet { get; set; }
        public Nullable<int> MaNguoiDanhGia { get; set; }
    }
}
