//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn
{
    using System;
    using System.Collections.Generic;
    
    public partial class NghiPhep
    {
        public int MaNghiPhep { get; set; }
        public Nullable<int> MaNhanVien { get; set; }
        public System.DateTime NgayBatDau { get; set; }
        public System.DateTime NgayKetThuc { get; set; }
        public string LoaiNghi { get; set; }
        public string LyDo { get; set; }
        public string TrangThai { get; set; }
        public Nullable<int> MaNguoiDuyet { get; set; }
    }
}
