//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhongBan
    {
        public int MaPhongBan { get; set; }
        public string TenPhongBan { get; set; }
        public string MoTa { get; set; }
        public Nullable<System.DateTime> NgayThanhLap { get; set; }
    }
}
